name: Java CI with Gradle

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21' 
        distribution: 'temurin'
        cache: 'gradle'

    - name: Grant execute permission for gradlew 
      run: chmod +x gradlew
      working-directory: serving-web-content/

    #- name: Build with Gradle and Run Tests 
    #  run: ./gradlew build 

   
    - name: Run Unit Tests Only
      run: ./gradlew test
      working-directory: serving-web-content/

#- name: Upload Test Report
#  if: always()
#  uses: actions/upload-artifact@v4
#  with:
#    name: test-report
#    path: build/reports/tests/test/ 
